fragment projectEntity on ProjectEntity {
  id
  attributes {
    title
    description
    resources {
      data {
        attributes {
          title
          url
          organization
        }
      }
    }
    thumbnails {
      data {
        attributes {
          name
          url
        }
      }
    }
    recipes {
      prompt
      script
    }
    tags {
      data {
        attributes {
          title
        }
      }
    }
    formattedFiles {
      data {
        attributes {
          name
          url
        }
      }
    }
    updatedAt
  }
}

query searchProject(
  $query: String!
  $filterVariables: ProjectFiltersInput
  $page: Int
) {
  search(query: $query) {
    projects(
      filters: $filterVariables
      pagination: { page: $page, pageSize: 10 }
    ) {
      data {
        ...projectEntity
      }
    }
  }
}

query filterProject($filterVariables: ProjectFiltersInput, $page: Int) {
  projects(
    filters: $filterVariables
    pagination: { page: $page, pageSize: 10 }
    sort: "updatedAt:desc"
  ) {
    data {
      ...projectEntity
    }
  }
}

query getProject($id: ID) {
  project(id: $id) {
    data {
      ...projectEntity
    }
  }
}
